Failover local file
wavelog/WaveLogGate pull request #24
Opened 2024-12-13 20:24 UTC by remy56k

I have a working example for https://github.com/wavelog/WaveLogGate/issues/23
If error (if WLG can not push QSO with success), the QSO is written in the specified file : 

![image](https://github.com/user-attachments/assets/26194813-df10-4a34-bb24-8055de53607e)

Import the resulting file with multiples QSO in the WaveLog web interface works fine.

Maybe we can improve/adapt GUI error messages when the QSO is logged in the file.

Test Ok on Ubuntu 22, cannot check on Windows atm.

2024-12-31 10:03 UTC, int2001 requested changes
i think the Window needs a bit more height. Otherwise it looks crappy.
still not a real friend of that feature.

Reason: People will ask over and over about that "Failover ADIF File" where WSJT-X produces its own file which can easily be uploaded with dupe-check enabled.

2024-12-31 14:28 UTC, int2001 commented
A few more things besides my considerations above(sorry!).
What about:
- checking if location exists? Otherwise the write would fail and the OP can't see it.
- a "folder-requester" modal where one can chose the path? (Should be doable with internal functions)

i learned from Wavelog itself: Everything needs to be bulletproof, because people are doing the wildest things...

2025-01-05 11:04 UTC, remy56k commented
Ok I understand. I'm not used to Electron so for now we can keep WLG as it. We will see later if this feature is requested.

2025-03-21 06:23 UTC, int2001 commented
closing this now, since the client (WSJT-X, FLDigi, $tool) always creates its own log and we don't want to raise complexity here

2025-03-21 06:23 UTC, closed without merging